-- 멘토님 답안
SELECT PD.PRODUCT_CODE, SUM(PD.PRICE * OFF.SALES_AMOUNT) AS SALES FROM PRODUCT PD, OFFLINE_SALE OFF
WHERE PD.PRODUCT_ID = OFF.PRODUCT_ID
GROUP BY PD.PRODUCT_CODE
ORDER BY SALES DESC, PD.PRODUCT_CODE ASC;