-- 코드를 입력하세요
# SELECT I.ANIMAL_ID, I.NAME 
# FROM ANIMAL_INS AS I
# INNER JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID = O.ANIMAL_ID
# WHERE I.DATETIME > O.DATETIME
# ORDER BY I.DATETIME

SELECT INS.ANIMAL_ID, INS.NAME FROM ANIMAL_INS INS
    JOIN ANIMAL_OUTS OUTS
    ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
    WHERE INS.DATETIME > OUTS.DATETIME
    ORDER BY INS.DATETIME
    